export function buildLearningBoardScreenUpsert({
  id,
  courseId,
  chapterId,
  module,
  chapter,
  screen,
  title,
  type,
  template,
  eyebrow,
  durationSeconds,
  narratorSegment,
  narratorText,
  narratorDuration,
  keyIdeaTitle,
  keyIdeaText,
  contentHtml,
  contentCss,
  contentJSON,
  createdAt,
  updatedAt,
}) {
  return {
    sql: `
      INSERT INTO learning_board_screens (
        id, course_id, chapter_id, module, chapter, screen,
        title, type, template, eyebrow,
        duration_seconds, narrator_segment, narrator_text, narrator_duration,
        key_idea_title, key_idea_text,
        content_html, content_css, content_json,
        created_at, updated_at
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(course_id, module, chapter, screen) DO UPDATE SET
        chapter_id = excluded.chapter_id,
        title = excluded.title,
        type = excluded.type,
        template = excluded.template,
        eyebrow = excluded.eyebrow,
        duration_seconds = excluded.duration_seconds,
        narrator_segment = excluded.narrator_segment,
        narrator_text = excluded.narrator_text,
        narrator_duration = excluded.narrator_duration,
        key_idea_title = excluded.key_idea_title,
        key_idea_text = excluded.key_idea_text,
        content_html = excluded.content_html,
        content_css = excluded.content_css,
        content_json = excluded.content_json,
        updated_at = excluded.updated_at
    `,
    args: [
      id,
      courseId,
      chapterId,
      module,
      chapter,
      screen,
      title,
      type,
      template,
      eyebrow,
      durationSeconds,
      narratorSegment,
      narratorText,
      narratorDuration,
      keyIdeaTitle,
      keyIdeaText,
      contentHtml,
      contentCss,
      contentJSON,
      createdAt,
      updatedAt,
    ],
  };
}
