FROM node:22-bookworm-slim

WORKDIR /app
COPY package*.json ./
COPY frontend/package*.json frontend/
COPY backend/package*.json backend/
RUN npm ci

COPY . .
CMD ["node", "scripts/run-azure-automation.js"]
